### ISSUE TITLE
Burn NixOS minimal into a USB stick using windows

### ISSUE THREAD

**Issue by dsalaza4** [kamadorueda/machine#1]
Some days ago I got a working laptop only with Windows.

I ended up having to download A linux-based OS just to be able to burn the image using the README.

I'd be nice to add a short guide on how to burn the image using powershell, CMD or usb burning tool. I personally think CMD or powershell are better because they do not require additional software.

**Comment by kamadorueda** [comment]
My go-to tool is: https://rufus.ie/en/ 

I'll add some docs

**Comment by kamadorueda** [comment]
Thanks for pointing this out, I have added my preferred tool for burning it on Windows. I have also used it before, so I know it works well by experience

---

![image](https://user-images.githubusercontent.com/47480384/137613513-32362f18-97ed-4aa1-a0bb-76261b6a7348.png)
